config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dashboard, only: [:index]
    resources :news
    post '/admin/news', to: '/admin/news#index'
    resources :events, only: [:index, :create, :destroy]
    post '/admin/events', to: '/admin/events#index'
    resources :technologies, only: [:index, :create, :destroy]
    post '/admin/technologies', to: '/admin/technologies#index'
    resources :organizations, only: [:index, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  resources :companies

  resources :events, only: [:index]

  resources :news

  resource :session, only: [:new, :create, :destroy]
  # resource :about, only: [:new]
  resources :users, only: [:new, :create]

  get('/about', { to: 'about#index' })
  get('/', { to: 'directories#index', as: 'home' })

end

app/views/partials/_admin_header.html.erb
<li class="nav-item"><a class="nav-link admin"> Admin Panel: </a></li>
<li class="nav-item mr-3"><a class="nav-link"<%= link_to 'Organizations', admin_dashboard_index_path %></a></li>
<li class="nav-item mr-3"><a class="nav-link"<%= link_to 'Events', admin_events_path %></a></li>
<li class="nav-item mr-3"><a class="nav-link"<%= link_to 'News', admin_news_index_path %></a></li>
<li class="nav-item mr-3"><a class="nav-link"<%= link_to 'Users', admin_users_path %></a></li>
<li class="nav-item"><a class="nav-link"<%= link_to 'Technologies', admin_technologies_path %></a></li>

app/views/partials/_header.html.erb
<li class="nav-item mr-4 ml-4"><a class="nav-link"<%= link_to 'Directory', home_path %></a></li>
<li class="nav-item mr-4"><a class="nav-link"<%= link_to 'Events', events_path %></a></li>
<li class="nav-item mr-4"><a class="nav-link"<%= link_to 'News', news_index_path %></a></li>
<% if current_user && current_user.admin? %>
  <li class="nav-item mr-4"><a class="nav-link text-light"<%= link_to 'Admin Panel', admin_dashboard_index_path %></a></li>
<% end %>
<li class="nav-item mr-4"><a class="nav-link text-light"<%= link_to 'Directory', home_path %></a></li>
<li class="nav-item mr-4"><a class="nav-link text-light"<%= link_to 'Events', events_path %></a></li>
<li class="nav-item mr-4"><a class="nav-link text-light"<%= link_to 'News', news_index_path %></a></li>