config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dashboard, only: [:index]
    resources :news
    post '/admin/news', to: '/admin/news#index'
    resources :events, only: [:index, :create, :destroy]
    post '/admin/events', to: '/admin/events#index'
    resources :technologies, only: [:index, :create, :destroy]
    post '/admin/technologies', to: '/admin/technologies#index'
    resources :organizations, only: [:index, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  resources :companies

  resources :events, only: [:index]

  resources :news

  resource :session, only: [:new, :create, :destroy]
  # resource :about, only: [:new]
  resources :users, only: [:new, :create]

  get('/about', { to: 'about#index' })
  get('/', { to: 'directories#index', as: 'home' })

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin!
  
  def index
    @companies = Company.all 
    # render admin_technologies_path
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do | format |
    format.html { redirect_to admin_organizations_path }
    format.json { head :no_content }
    format.js   { render :layout => false }
    end
  end

  private
  
end

app/views/admin/organizations/destroy.js.erb
$('.delete_organization').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
}); 

app/views/admin/organizations/index.html.erb
<div class="container">
  <h2 class="title">Organizations</h2>
  <%= link_to "Add", new_company_path, class: "mt-4 btn btn-danger" %>

  <table class="table table-borderless mt-5">
    <thead>
      <tr>
        <th scope="col">Organization Name</th>
        <th scope="col">Published?</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @companies.each do |c| %>
      <tr id="<%= c.id %>">
        <td>
          <%= c.name %>
        </td>
        <td>
          <%= c.published %>
        </td>
        <td>
          <p>
            <%= link_to(
              "Show", 
              company_path(c.id),
              method: :get
            ) %>
            <%= link_to(
              "Edit",
              edit_company_path(c.id)
            ) %>
            <%= link_to(
              "Remove",
              admin_organization_path(c.id),
              method: :delete, 
              data: { confirm: 'Are you sure?' },
              :remote => true,
              :class => 'delete_organization text-light'
            ) %>
          </p>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>